# Generated by Django 5.2.6 on 2025-09-23 20:35

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TileUsageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(blank=True, choices=[('ceramic', 'Ceramic'), ('porcelain', 'Porcelain'), ('marble', 'Marble'), ('granite', 'Granite'), ('wood', 'Wood'), ('glass', 'Glass'), ('stone', 'Stone'), ('forever', 'Forever')], max_length=100, null=True)),
                ('finish', models.CharField(blank=True, choices=[('matte', 'Matte'), ('glossy', 'Glossy'), ('satin', 'Satin'), ('textured', 'Textured')], max_length=50, null=True)),
                ('design', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_label', models.CharField(blank=True, default='Offer Price Rs', help_text='Prefix for price display', max_length=100, null=True)),
                ('suitable_for', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bathroom', 'Bathroom Tiles'), ('living_room', 'Living Room Tiles'), ('bedroom', 'Bedroom Tiles'), ('accent', 'Accent Tiles'), ('hospital', 'Hospital Tiles'), ('high_traffic', 'High Traffic Tiles'), ('bar', 'Bar/Restaurant'), ('commercial', 'Commercial/Office'), ('outdoor', 'Outdoor Area')], max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tiles/')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sqft', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.cart')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tile')),
            ],
            options={
                'unique_together': {('cart', 'tile')},
            },
        ),
    ]
