# Generated by Django 5.2.6 on 2025-09-24 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='trending/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='trending/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='trending/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tile')),
            ],
        ),
    ]
