# Generated by Django 5.2.6 on 2025-09-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='img3',
        ),
        migrations.CreateModel(
            name='TrendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trending/')),
                ('trending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.trending')),
            ],
        ),
    ]
