# Generated by Django 5.2.6 on 2025-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_trending_img1_remove_trending_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='trending/'),
        ),
        migrations.AddField(
            model_name='trending',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='trending/'),
        ),
        migrations.AddField(
            model_name='trending',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='trending/'),
        ),
        migrations.DeleteModel(
            name='TrendingImage',
        ),
    ]
